### PR TITLE
Demonstrate version matchers as test strategy

### PR DESCRIPTION
**Pull request by timtebeek**
## What's changed?
Use `spec.after()` to match expected vs actual after recipe run.

## What's your motivation?
This ensures we don't have to update the tests after every new release.

## Anything in particular you'd like reviewers to focus on?
Would you want to continue this approach for the other [tests using 4.0.0-M8](https://github.com/search?q=repo%3Aopenrewrite%2Frewrite-micronaut%204.0.0-M8&type=code) ?

## Have you considered any alternatives or workarounds?
Not a fan of using constants, but that could work as well.
Or keep updating the tests with each new release.

### CODE REVIEW

**Comment by jeremyg484** [comment]
@timtebeek After reviewing this and giving it some more thought, I think I'm still going to hold off on applying this approach until after we get the patch release out to support Micronaut Framework 4.0.0 GA.

Even with this approach as demonstrated, we'd still need to change the tests every time, because there is still the explicit version of the Micronaut gradle plugin in the "initial" state. Ultimately I'd like to actually parameterize that version in the initial state so that we're always testing against the latest version of the plugin (and the latest version of the overall Micronaut platform, etc.).

I will push up a draft PR shortly that maintains the existing approach in the tests, but does also switch to using version patterns in the recipes themselves.

**Comment by timtebeek** [comment]
Ah I hadn't considered the initial here; Could we have the initial just read a stable 3.x line that you want to upgrade to 4.x? That'd be more in line with what I would expect in terms of recipe in and outputs, as compared to elsewhere.

**Comment by jeremyg484** [comment]
> Ah I hadn't considered the initial here; Could we have the initial just read a stable 3.x line that you want to upgrade to 4.x? That'd be more in line with what I would expect in terms of recipe in and outputs, as compared to elsewhere.

Yes, that would be a possibility, but I guess I've been approaching many of these tests (and this would be one such case) as though that version upgrade step has already happened. In this particular case, the Micronaut version shouldn't ever really change based on the particular recipe being tested here. I'm going to give some more thought as to how to best address that once I'm able to run tests that can successfully resolve 4.x.

**Comment by timtebeek** [comment]
Superseded by #81

**Pull request closed without merging**
